dev to main
roller-coaster-94/put-together-server pull request #2
Opened 2022-08-18 14:09 UTC by jhkang1517

dev branch -> main branch

- Spring boot Version 2.7.2
- Gradle
- Java 17
- Github Action 적용 완료

2022-08-22 09:35 UTC, krhong23 commented on src/main/java/kr/co/puttogether/assembly/controller/AssemblyController.java
> +@RequestMapping("/assembly")
조립기/분해기를 통합할 수 있는 네이밍 고려 부탁드려요

2022-08-22 09:37 UTC, krhong23 commented on src/main/java/kr/co/puttogether/assembly/domain/Assembly.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Id 생성 전략 고민해보기

2022-08-23 12:03 UTC, jhkang1517 commented on src/main/java/kr/co/puttogether/assembly/controller/AssemblyController.java
> +@RequestMapping("/assembly")
키보드가 주 도메인인 만큼, 접두사 keyboard 가 어떤 도메인이든 앞에 붙는 다는 가정 하에,

- essay (수필, 어떤 논제, 문제에 대한 짧은 글)
- journal (특정 주제나 전문 분야를 다루는 신문, 학술지 등)
- paper (서류, 문서, 논문, 과제물)

이런 단어들을 사용하는 것이 좋아보이는데... 저는 에세이 정도가 적절해보입니다.

`assembly -> essay`

2022-08-23 12:04 UTC, jhkang1517 commented on src/main/java/kr/co/puttogether/assembly/domain/Assembly.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
IDENTITY 와 SEQUENCE 중에서 고르면 될 것 같습니다.

저희 프로젝트에서 둘 중 특별히 성능상 이점을 가진 전략은 없는 것으로 보입니다.
postgreSQL은 IDENTITY, SEQUENCE 둘 다 지원하기 때문에 DB에 따라 선택할 필요도 없습니다.

다만 SEQUENCE는 JPA Entity 마다 별도의 시퀀스, 그리고 시퀀스제네레이터를 생성하여야 하기 때문에 저는 코드 양을 더 줄일 수 있는 IDENTITY 가 적절해 보입니다.

2022-08-27 14:11 UTC, krhong23 requested changes
프로젝트 구조는 현재 버전으로 가면 될 것 같습니다~ 의견주신 Eaasy 도메인명만 변경하면 될 것 같네요~

2022-08-27 14:11 UTC, krhong23 commented on src/main/java/kr/co/puttogether/assembly/domain/Assembly.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
좋습니다. 아직 ID 자동 생성 전략에 대해서 더 탐구하고 있긴 합니다만
트랜잭션을 지원하는 쓰기 지연을 할 수 없는 IDENTITY 전략도 무방할 것 같습니다.
해당 주제에 대해서는 더 찾아보고 정리해두면 JPA를 이해하는데에 도움이 될 것 같다는 생각이 듭니다.

2022-08-29 13:31 UTC, merged